lr: 0.00005
gpu_id: 0
epochs: 100
seed: 19950919
train_batch_size: 8
test_batch_size: 16
num_workers: 16
device_id: [0, 1, 2, 3]
bert_version: 'bert-base-uncased'

dataset: 'EURLex-4k'

use_checkpoint: False
checkpoint_epoch: 0
